"""baseline 2026-05

Revision ID: 99691740424c
Revises: 
Create Date: 2026-05-11 03:24:29.399062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99691740424c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled_by_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('billing_cycle', sa.String(length=10), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=60), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=60), nullable=True),
    sa.Column('bank_sync_last_at', sa.DateTime(), nullable=True),
    sa.Column('bank_sync_count_today', sa.Integer(), nullable=True),
    sa.Column('bank_sync_count_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('grace_ends_at', sa.DateTime(), nullable=True),
    sa.Column('addons', sa.String(length=255), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('data_retention_until', sa.DateTime(), nullable=True),
    sa.Column('trial_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('companies', sa.String(length=500), nullable=True),
    sa.Column('federal_tax_rate', sa.Float(), nullable=False),
    sa.Column('referred_by_code_id', sa.Integer(), nullable=True),
    sa.Column('referee_credit_applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_code_id'], ['referral_code.id'], name='fk_store_referred_by_code', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tv_bank_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tv_bank_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_bank_catalog_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tv_bank_catalog_slug'), ['slug'], unique=True)

    op.create_table('tv_catalog_logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_type', sa.String(length=8), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('mime_type', sa.String(length=40), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_type', 'slug', name='uq_tv_catalog_logo_type_slug')
    )
    with op.batch_alter_table('tv_catalog_logo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_catalog_logo_catalog_type'), ['catalog_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tv_catalog_logo_slug'), ['slug'], unique=False)

    op.create_table('tv_company_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tv_company_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_company_catalog_slug'), ['slug'], unique=True)

    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_event_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_event_status'), ['status'], unique=False)

    op.create_table('ach_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('ach_date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=False),
    sa.Column('batch_ref', sa.String(length=60), nullable=False),
    sa.Column('ach_amount', sa.Float(), nullable=False),
    sa.Column('transfer_dates', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'batch_ref')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_country', sa.String(length=8), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'phone_country', 'phone_number', name='uq_customer_store_phone')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('ix_customer_phone', ['phone_country', 'phone_number'], unique=False)

    op.create_table('monthly_financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('taxable_sales', sa.Float(), nullable=True),
    sa.Column('non_taxable', sa.Float(), nullable=True),
    sa.Column('bill_payment_charge', sa.Float(), nullable=True),
    sa.Column('phone_recargas', sa.Float(), nullable=True),
    sa.Column('boost_mobile', sa.Float(), nullable=True),
    sa.Column('check_cashing_fees', sa.Float(), nullable=True),
    sa.Column('return_check_hold_fees', sa.Float(), nullable=True),
    sa.Column('rebates_commissions', sa.Float(), nullable=True),
    sa.Column('mt_commission_in_bank', sa.Float(), nullable=True),
    sa.Column('other_income_1', sa.Float(), nullable=True),
    sa.Column('other_income_2', sa.Float(), nullable=True),
    sa.Column('other_income_3', sa.Float(), nullable=True),
    sa.Column('cash_purchases', sa.Float(), nullable=True),
    sa.Column('check_purchases', sa.Float(), nullable=True),
    sa.Column('cash_expenses', sa.Float(), nullable=True),
    sa.Column('check_expenses', sa.Float(), nullable=True),
    sa.Column('cash_payroll', sa.Float(), nullable=True),
    sa.Column('bank_charges_210', sa.Float(), nullable=True),
    sa.Column('bank_charges_230', sa.Float(), nullable=True),
    sa.Column('bank_charges_total', sa.Float(), nullable=True),
    sa.Column('credit_card_fees', sa.Float(), nullable=True),
    sa.Column('money_order_rent', sa.Float(), nullable=True),
    sa.Column('emaginenet_tech', sa.Float(), nullable=True),
    sa.Column('irs_payroll_tax', sa.Float(), nullable=True),
    sa.Column('texas_workforce', sa.Float(), nullable=True),
    sa.Column('other_taxes', sa.Float(), nullable=True),
    sa.Column('accounting_charges', sa.Float(), nullable=True),
    sa.Column('return_check_gl', sa.Float(), nullable=True),
    sa.Column('other_expense_1', sa.Float(), nullable=True),
    sa.Column('other_expense_2', sa.Float(), nullable=True),
    sa.Column('other_expense_3', sa.Float(), nullable=True),
    sa.Column('other_expense_4', sa.Float(), nullable=True),
    sa.Column('other_expense_5', sa.Float(), nullable=True),
    sa.Column('over_short', sa.Float(), nullable=True),
    sa.Column('borrowed_money_return', sa.Float(), nullable=True),
    sa.Column('profit_distributed', sa.Float(), nullable=True),
    sa.Column('cash_carry_forward', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'year', 'month')
    )
    op.create_table('mt_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('federal_tax', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'report_date', 'company')
    )
    op.create_table('referral_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('owner_store_id', sa.Integer(), nullable=False),
    sa.Column('reward_self_cents', sa.Integer(), nullable=True),
    sa.Column('reward_referee_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('redeemed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('owner_store_id')
    )
    op.create_table('store_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_employee_store_id'), ['store_id'], unique=False)

    op.create_table('stripe_bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=60), nullable=False),
    sa.Column('institution_name', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('last4', sa.String(length=8), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('subcategory', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('last_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('last_balance_as_of', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    with op.batch_alter_table('stripe_bank_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_bank_account_store_id'), ['store_id'], unique=False)

    op.create_table('tv_display',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('subtitle', sa.String(length=120), nullable=True),
    sa.Column('orientation', sa.String(length=16), nullable=True),
    sa.Column('theme', sa.String(length=16), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pair_code', sa.String(length=8), nullable=True),
    sa.Column('pair_code_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('theme_preference', sa.String(length=8), nullable=True),
    sa.Column('notify_trial_reminders', sa.Boolean(), nullable=True),
    sa.Column('notify_announcement_email', sa.Boolean(), nullable=True),
    sa.Column('email_bounced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)

    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('broadcast_requested', sa.Boolean(), nullable=True),
    sa.Column('broadcast_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('desc_match_type', sa.String(length=20), nullable=True),
    sa.Column('desc_match_value', sa.String(length=500), nullable=True),
    sa.Column('sign_filter', sa.String(length=10), nullable=True),
    sa.Column('amount_min_cents', sa.Integer(), nullable=True),
    sa.Column('amount_max_cents', sa.Integer(), nullable=True),
    sa.Column('account_filter_id', sa.Integer(), nullable=True),
    sa.Column('target_kind', sa.String(length=40), nullable=False),
    sa.Column('auto_post', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('last_matched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_filter_id'], ['stripe_bank_account.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_rule_store_id'), ['store_id'], unique=False)

    op.create_table('check_deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('deposit_time', sa.Time(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_deposit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_deposit_store_id'), ['store_id'], unique=False)

    op.create_table('daily_drop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('drop_time', sa.Time(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_drop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_drop_store_id'), ['store_id'], unique=False)

    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('taxable_sales', sa.Float(), nullable=True),
    sa.Column('non_taxable', sa.Float(), nullable=True),
    sa.Column('sales_tax', sa.Float(), nullable=True),
    sa.Column('bill_payment_charge', sa.Float(), nullable=True),
    sa.Column('phone_recargas', sa.Float(), nullable=True),
    sa.Column('boost_mobile', sa.Float(), nullable=True),
    sa.Column('money_transfer', sa.Float(), nullable=True),
    sa.Column('money_order', sa.Float(), nullable=True),
    sa.Column('check_cashing_fees', sa.Float(), nullable=True),
    sa.Column('return_check_hold_fees', sa.Float(), nullable=True),
    sa.Column('return_check_paid_back', sa.Float(), nullable=True),
    sa.Column('forward_balance', sa.Float(), nullable=True),
    sa.Column('from_bank', sa.Float(), nullable=True),
    sa.Column('other_cash_in', sa.Float(), nullable=True),
    sa.Column('rebates_commissions', sa.Float(), nullable=True),
    sa.Column('cash_purchases', sa.Float(), nullable=True),
    sa.Column('cash_expense', sa.Float(), nullable=True),
    sa.Column('check_purchases', sa.Float(), nullable=True),
    sa.Column('check_expense', sa.Float(), nullable=True),
    sa.Column('outside_cash_drops', sa.Float(), nullable=True),
    sa.Column('cash_deposit', sa.Float(), nullable=True),
    sa.Column('checks_deposit', sa.Float(), nullable=True),
    sa.Column('safe_balance', sa.Float(), nullable=True),
    sa.Column('payroll_expense', sa.Float(), nullable=True),
    sa.Column('other_cash_out', sa.Float(), nullable=True),
    sa.Column('over_short', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locked_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'report_date')
    )
    op.create_table('discount_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('amount_off_cents', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=16), nullable=True),
    sa.Column('duration_in_months', sa.Integer(), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redeemed_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_coupon_id', sa.String(length=60), nullable=True),
    sa.Column('stripe_promotion_code_id', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('email_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=80), nullable=True),
    sa.Column('to_addr', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('bounce_type', sa.String(length=16), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_event_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_event_to_addr'), ['to_addr'], unique=False)

    op.create_table('login_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_event_at'), ['at'], unique=False)
        batch_op.create_index('ix_login_event_at_user', ['at', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_event_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_event_user_id'), ['user_id'], unique=False)

    op.create_table('operator_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=60), nullable=True),
    sa.Column('target_label', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_audit_log_store_id'), ['store_id'], unique=False)

    op.create_table('owner_connect_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('used_by_store_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['used_by_store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('passkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('aaguid', sa.String(length=36), nullable=True),
    sa.Column('transports', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint')
    )
    op.create_table('recovery_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code_hash', name='uq_recovery_user_code')
    )
    op.create_table('referral_redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_code_id', sa.Integer(), nullable=False),
    sa.Column('referee_store_id', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('self_credit_applied_at', sa.DateTime(), nullable=True),
    sa.Column('referee_credit_applied_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_self_txn_id', sa.String(length=60), nullable=True),
    sa.Column('stripe_referee_txn_id', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['referee_store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['referral_code_id'], ['referral_code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referee_store_id')
    )
    op.create_table('return_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('bounced_on', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('check_number', sa.String(length=40), nullable=True),
    sa.Column('payer_bank', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_changed_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_check_store_id'), ['store_id'], unique=False)

    op.create_table('store_feature_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('flag_key', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'flag_key')
    )
    op.create_table('store_owner_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'store_id')
    )
    with op.batch_alter_table('store_owner_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_owner_link_store_id'), ['store_id'], unique=False)

    op.create_table('superadmin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_name', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=60), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('send_date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('send_amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('federal_tax', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('recipient_name', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('recipient_phone', sa.String(length=40), nullable=True),
    sa.Column('sender_phone', sa.String(length=40), nullable=True),
    sa.Column('sender_phone_country', sa.String(length=8), nullable=True),
    sa.Column('sender_address', sa.String(length=255), nullable=True),
    sa.Column('sender_dob', sa.Date(), nullable=True),
    sa.Column('confirm_number', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('status_notes', sa.String(length=255), nullable=True),
    sa.Column('batch_id', sa.String(length=60), nullable=True),
    sa.Column('internal_notes', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employee_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['store_employee.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.create_index('ix_transfer_confirm_number', ['confirm_number'], unique=False)
        batch_op.create_index('ix_transfer_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_transfer_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_transfer_status', ['status'], unique=False)
        batch_op.create_index('ix_transfer_store_send_date', ['store_id', 'send_date'], unique=False)

    op.create_table('tv_display_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=True),
    sa.Column('country_name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('mt_companies', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['display_id'], ['tv_display.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tv_display_country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_display_country_display_id'), ['display_id'], unique=False)

    op.create_table('tv_pairing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=48), nullable=False),
    sa.Column('device_label', sa.String(length=80), nullable=True),
    sa.Column('paired_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['display_id'], ['tv_display.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    with op.batch_alter_table('tv_pairing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_pairing_display_id'), ['display_id'], unique=False)

    op.create_table('daily_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('at_time', sa.Time(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('return_check_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['return_check_id'], ['return_check.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_line_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_line_item_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_line_item_store_id'), ['store_id'], unique=False)

    op.create_table('return_check_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_check_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['return_check_id'], ['return_check.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_check_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_check_payment_return_check_id'), ['return_check_id'], unique=False)

    op.create_table('transfer_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employee_name', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['store_employee.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_audit_store_id'), ['store_id'], unique=False)

    op.create_table('tv_display_payout_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tv_display_country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tv_display_payout_bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_display_payout_bank_country_id'), ['country_id'], unique=False)

    op.create_table('tv_pending_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('device_token', sa.String(length=48), nullable=False),
    sa.Column('device_label', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_pairing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_pairing_id'], ['tv_pairing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tv_pending_pair', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_pending_pair_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_tv_pending_pair_device_token'), ['device_token'], unique=True)

    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('stripe_bank_account_id', sa.Integer(), nullable=False),
    sa.Column('stripe_transaction_id', sa.String(length=80), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('category_slug', sa.String(length=60), nullable=True),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('daily_line_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_line_item_id'], ['daily_line_item.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['stripe_bank_account_id'], ['stripe_bank_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_transaction_id')
    )
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_bank_transaction_store_posted', ['store_id', 'posted_at'], unique=False)

    op.create_table('tv_display_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('mt_company', sa.String(length=80), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['tv_display_payout_bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'mt_company', name='uq_tvrate_bank_company')
    )
    with op.batch_alter_table('tv_display_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tv_display_rate_bank_id'), ['bank_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_display_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_display_rate_bank_id'))

    op.drop_table('tv_display_rate')
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_bank_transaction_store_posted')

    op.drop_table('bank_transaction')
    with op.batch_alter_table('tv_pending_pair', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_pending_pair_device_token'))
        batch_op.drop_index(batch_op.f('ix_tv_pending_pair_code'))

    op.drop_table('tv_pending_pair')
    with op.batch_alter_table('tv_display_payout_bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_display_payout_bank_country_id'))

    op.drop_table('tv_display_payout_bank')
    with op.batch_alter_table('transfer_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_audit_store_id'))

    op.drop_table('transfer_audit')
    with op.batch_alter_table('return_check_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_check_payment_return_check_id'))

    op.drop_table('return_check_payment')
    with op.batch_alter_table('daily_line_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_line_item_store_id'))
        batch_op.drop_index(batch_op.f('ix_daily_line_item_kind'))

    op.drop_table('daily_line_item')
    with op.batch_alter_table('tv_pairing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_pairing_display_id'))

    op.drop_table('tv_pairing')
    with op.batch_alter_table('tv_display_country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_display_country_display_id'))

    op.drop_table('tv_display_country')
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_index('ix_transfer_store_send_date')
        batch_op.drop_index('ix_transfer_status')
        batch_op.drop_index('ix_transfer_customer_id')
        batch_op.drop_index('ix_transfer_created_by')
        batch_op.drop_index('ix_transfer_confirm_number')

    op.drop_table('transfer')
    op.drop_table('superadmin_audit_log')
    with op.batch_alter_table('store_owner_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_owner_link_store_id'))

    op.drop_table('store_owner_link')
    op.drop_table('store_feature_override')
    with op.batch_alter_table('return_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_check_store_id'))

    op.drop_table('return_check')
    op.drop_table('referral_redemption')
    op.drop_table('recovery_code')
    op.drop_table('push_subscription')
    op.drop_table('password_reset_token')
    op.drop_table('passkey')
    op.drop_table('owner_connect_code')
    with op.batch_alter_table('operator_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_audit_log_store_id'))

    op.drop_table('operator_audit_log')
    with op.batch_alter_table('login_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_event_role'))
        batch_op.drop_index('ix_login_event_at_user')
        batch_op.drop_index(batch_op.f('ix_login_event_at'))

    op.drop_table('login_event')
    with op.batch_alter_table('email_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_event_to_addr'))
        batch_op.drop_index(batch_op.f('ix_email_event_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_email_event_created_at'))

    op.drop_table('email_event')
    op.drop_table('discount_code')
    op.drop_table('daily_report')
    with op.batch_alter_table('daily_drop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_drop_store_id'))

    op.drop_table('daily_drop')
    with op.batch_alter_table('check_deposit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_deposit_store_id'))

    op.drop_table('check_deposit')
    with op.batch_alter_table('bank_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_rule_store_id'))

    op.drop_table('bank_rule')
    op.drop_table('announcement')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    op.drop_table('tv_display')
    with op.batch_alter_table('stripe_bank_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_bank_account_store_id'))

    op.drop_table('stripe_bank_account')
    with op.batch_alter_table('store_employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_employee_store_id'))

    op.drop_table('store_employee')
    op.drop_table('referral_code')
    op.drop_table('mt_summary')
    op.drop_table('monthly_financial')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_phone')

    op.drop_table('customer')
    op.drop_table('ach_batch')
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_event_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_event_received_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_event_event_type'))

    op.drop_table('webhook_event')
    with op.batch_alter_table('tv_company_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_company_catalog_slug'))

    op.drop_table('tv_company_catalog')
    with op.batch_alter_table('tv_catalog_logo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_catalog_logo_slug'))
        batch_op.drop_index(batch_op.f('ix_tv_catalog_logo_catalog_type'))

    op.drop_table('tv_catalog_logo')
    with op.batch_alter_table('tv_bank_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tv_bank_catalog_slug'))
        batch_op.drop_index(batch_op.f('ix_tv_bank_catalog_country_code'))

    op.drop_table('tv_bank_catalog')
    op.drop_table('store')
    op.drop_table('feature_flag')
    # ### end Alembic commands ###
