"""Auth — Services. Composes Repository SQL with the JWT issuer +
password-flow business logic. The Controller layer (PR 20+) wires
these to HTTP routes.
"""
from api.Modules.Auth.Services.jwt_issuer import (
    DEFAULT_PENDING_2FA_TTL_SECONDS,
    JWTIssuer,
    decode_access_token,
    decode_pending_2fa_token,
    issue_access_token,
    issue_pending_2fa_token,
)
from api.Modules.Auth.Services.login import (
    LoginPendingResult,
    LoginResult,
    TotpEnrollmentRequired,
    authenticate_password,
    authenticate_password_cross_store,
    confirm_recovery_codes_saved,
    finalize_2fa_with_recovery_code,
    finalize_2fa_with_totp,
    finish_totp_enrollment,
    permissions_for,
    start_totp_enrollment,
    verify_password_cross_store,
)
from api.Modules.Auth.Services.password_change import (
    MIN_PASSWORD_LENGTH,
    admin_set_password,
    change_password,
)
from api.Modules.Auth.Services.passkey import (
    RP_NAME as PASSKEY_RP_NAME,
    exclude_credentials as passkey_exclude_credentials,
    is_eligible as passkey_is_eligible,
    origin as passkey_origin,
    rp_id as passkey_rp_id,
    rp_name as passkey_rp_name,
)
from api.Modules.Auth.Services.notifications import (
    get_notifications_payload,
    trial_toggle_applies,
    update_notifications,
)
from api.Modules.Auth.Services.password_reset import (
    IssuedToken,
    consume_password_reset_token,
    hash_token,
    issue_password_reset_token,
    verify_password_reset_token,
)
from api.Modules.Auth.Services.profile import (
    TIMEZONE_CHOICES as PROFILE_TIMEZONE_CHOICES,
    ProfileValidationError,
    get_profile_payload,
    update_profile,
)
from api.Modules.Auth.Services.signup import (
    DEFAULT_GRACE_DAYS,
    DEFAULT_TRIAL_DAYS,
    OwnerSignupResult,
    SignupConflictError,
    SignupResult,
    create_owner,
    create_store_and_admin,
)
from api.Modules.Auth.Services.totp import (
    RECOVERY_CODES_PER_USER,
    TOTP_VALID_WINDOW,
    consume_recovery_code,
    format_recovery_code,
    generate_recovery_codes,
    hash_recovery_code,
    is_enrolled,
    needs_totp,
    verify_totp_token,
)

__all__ = [
    "DEFAULT_GRACE_DAYS",
    "DEFAULT_TRIAL_DAYS",
    "IssuedToken",
    "DEFAULT_PENDING_2FA_TTL_SECONDS",
    "JWTIssuer",
    "LoginPendingResult",
    "LoginResult",
    "MIN_PASSWORD_LENGTH",
    "OwnerSignupResult",
    "PASSKEY_RP_NAME",
    "PROFILE_TIMEZONE_CHOICES",
    "ProfileValidationError",
    "RECOVERY_CODES_PER_USER",
    "SignupConflictError",
    "SignupResult",
    "TOTP_VALID_WINDOW",
    "TotpEnrollmentRequired",
    "admin_set_password",
    "authenticate_password",
    "authenticate_password_cross_store",
    "change_password",
    "confirm_recovery_codes_saved",
    "consume_password_reset_token",
    "consume_recovery_code",
    "create_owner",
    "create_store_and_admin",
    "decode_access_token",
    "decode_pending_2fa_token",
    "finalize_2fa_with_recovery_code",
    "finalize_2fa_with_totp",
    "finish_totp_enrollment",
    "format_recovery_code",
    "generate_recovery_codes",
    "get_notifications_payload",
    "get_profile_payload",
    "hash_recovery_code",
    "hash_token",
    "is_enrolled",
    "issue_access_token",
    "issue_password_reset_token",
    "issue_pending_2fa_token",
    "needs_totp",
    "start_totp_enrollment",
    "passkey_exclude_credentials",
    "passkey_is_eligible",
    "passkey_origin",
    "passkey_rp_id",
    "passkey_rp_name",
    "permissions_for",
    "trial_toggle_applies",
    "update_notifications",
    "update_profile",
    "verify_password_cross_store",
    "verify_password_reset_token",
    "verify_totp_token",
]
